# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llma < Formula
  desc "LLMariner transforms your GPU clusters into a powerhouse for generative AI workloads."
  homepage "https://llmariner.ai"
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/llmariner/llmariner/releases/download/v1.1.1/llmariner_Darwin_x86_64.tar.gz"
      sha256 "170d05b4e7352619f742750f0092df9657efcf064368351145a759117d5afef1"

      def install
        bin.install "llma"
      end
    end
    on_arm do
      url "https://github.com/llmariner/llmariner/releases/download/v1.1.1/llmariner_Darwin_arm64.tar.gz"
      sha256 "d5689e566488256a9948c5f2c529c806eac53a2f7ca8785be107a712a30df075"

      def install
        bin.install "llma"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/llmariner/llmariner/releases/download/v1.1.1/llmariner_Linux_x86_64.tar.gz"
        sha256 "9f00419b00c25ddce3d1abf5c1bdd37776863c49856e9c188672b9c597761df7"

        def install
          bin.install "llma"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/llmariner/llmariner/releases/download/v1.1.1/llmariner_Linux_arm64.tar.gz"
        sha256 "cb5fdd033b39db8e7372c910e15a537dc3f070cc3c1ee033d88050b14c049db2"

        def install
          bin.install "llma"
        end
      end
    end
  end
end
