# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llma < Formula
  desc "LLMariner transforms your GPU clusters into a powerhouse for generative AI workloads."
  homepage "https://llmariner.ai"
  version "1.39.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/llmariner/llmariner/releases/download/v1.39.3/llmariner_Darwin_x86_64.tar.gz"
      sha256 "7fffb9221abddf9e1217e288840d3f71959a4207107ef9e113f492d1f1668201"

      def install
        bin.install "llma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/llmariner/llmariner/releases/download/v1.39.3/llmariner_Darwin_arm64.tar.gz"
      sha256 "e82fbe12468b5b51228570b4a05a1d64a65a1e21616529369820d91d567cb361"

      def install
        bin.install "llma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/llmariner/llmariner/releases/download/v1.39.3/llmariner_Linux_x86_64.tar.gz"
      sha256 "906d7f97ed0169c97846a308680f51d19f80e4a91c1fe73277f9a3ab2860c776"
      def install
        bin.install "llma"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/llmariner/llmariner/releases/download/v1.39.3/llmariner_Linux_arm64.tar.gz"
      sha256 "34e15c551205ad3bcdb68b6ee83de3e7c74929004b30172653fa63a9dc29a6bc"
      def install
        bin.install "llma"
      end
    end
  end
end
